FROM node
MAINTAINER radu micu <radu.micu@gmail.com>

RUN mkdir -p /usr/src/webapp
WORKDIR /usr/src/webapp

COPY package.json /usr/src/webapp

RUN npm install

COPY app /usr/src/webapp/
COPY test /usr/src/webapp/

ENV NODE_ENV development

EXPOSE 9000

# In addition to the shell's pre-existing PATH,
# npm run adds node_modules/.bin to the PATH provided to scripts.
CMD ["npm", "run", "start"]
